name: api_example
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  json_annotation: ^4.0.1
  dio: ^4.0.0
  flutter_bloc: ^7.0.1
  webview_flutter: ^2.0.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.3
  build_runner: ^2.0.4

flutter:

  uses-material-design: true

  assets:
    - assets/icons/


  fonts:
    - family: GoogleSans
      fonts:
        - asset: fonts/GoogleSansRegular.ttf